name: nocab_core
description: Core library for nocab transfer
version: 1.0.0
repository: https://github.com/nocab_transfer/nocab_core

publish_to: none

environment:
  sdk: '>=3.0.0-1 <4.0.0'

dependencies:
  path: ^1.8.3
  uuid: ^3.0.7
  nocab_logger:
    git:
      url: https://github.com/nocab-transfer/nocab-logger

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
